src/a_scraping_service/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import include

from a_scraping_service.views import main_index

urlpatterns = [
    path('', main_index, name = 'main_index'),
    path('admin/', admin.site.urls),
    path('scraping/', include('scraping.urls', namespace='scraping')), #urls.py из приложения scraping (urls.py)
    path('accounts/', include('accounts.urls', namespace='accounts')), #urls.py из приложения accounts (urls.py)
]

src/accounts/urls.py
from django.urls import path

from accounts.views import login_views, logout_views, register_views

app_name = 'accounts'

urlpatterns = [
    path('login_views', login_views, name = 'login_views'),
    path('logout_views', logout_views, name = 'logout_views'),
    path('register_views', register_views, name = 'register_views'),
]

src/scraping/urls.py
from django.urls import path

from scraping.views import main_navbar

app_name = 'scraping'

urlpatterns = [
    path('', main_navbar, name = 'main_navbar'),
]

src/scraping/models.py
from django.db import models
from django.template.defaultfilters import slugify


class City(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Наименование города')
    slug = models.CharField(max_length=50, unique=True)

    class Meta:
        verbose_name='Город'
        verbose_name_plural = 'Города'

    def __str__(self):
        return self.name
#------------------------------------------автоматическое формирование поля slug из поля name-----------------
#поле SlugAutoField - формирует слаги только из латинских букв (так же как и функция slugify(name)
    #def save(self, *args, **kwargs):
        #if not self.slug:
            #self.slug = slugify(self.name)
        #super(City, self).save(*args, **kwargs)
#-------------------------------------------------------------------------------------------------------------
class Specialization(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Наименование специальности')
    slug = models.CharField(max_length=50, unique=True)

    class Meta:
        verbose_name = 'Специальность'
        verbose_name_plural = 'Специальности'

    def __str__(self):
        return self.name

class Vacancy(models.Model):
    url = models.URLField(unique=True)
    title = models.CharField(max_length=250, verbose_name='Заголовок вакансии')
    company =models.CharField(max_length=250, verbose_name='Работодатель')
    description = models.TextField(verbose_name='Описание вакансии')
    city = models.ForeignKey('City', on_delete=models.CASCADE, verbose_name='Город')
    specialization = models.ForeignKey('Specialization', on_delete=models.CASCADE, verbose_name='Специальность')
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата/Время создания записи')

    class Meta:
        verbose_name = 'Вакансия'
        verbose_name_plural = 'Вакансии'

    def __str__(self):
        return self.title

src/scraping/forms.py
from django import forms
from scraping.models import City, Specialization


class FindForm(forms.Form):

    city = forms.ModelChoiceField(queryset=City.objects.all(), #заполнит форму выбора списком обэектов из БД
                                  to_field_name="slug", #обратиться к параметру slug у конкретной модели
                                  required=False, #False - можно оставлять незаполненным
                                  label='Выбирете город для поиска',
                                  empty_label='-------------------------------- ',
                                  widget=forms.Select(attrs={'class': 'любой класс CSS для оформления формы'}))

    specialization = forms.ModelChoiceField(queryset=Specialization.objects.all(), #заполнит форму выбора списком обэектов из БД
                                            to_field_name="slug", #обратиться к параметру slug у конкретной модели
                                            required=False, #False - можно оставлять незаполненным
                                            label='Выбирете специальность',
                                            empty_label='------------------------------------- ',
                                            widget=forms.Select(attrs={'class': 'любой класс CSS для оформления формы'}))

src/scraping/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from .models import Vacancy
from .forms import FindForm

def main_navbar(request):

    form = FindForm() #форма для выбора города и сециальности для поиска (scraping/forms.py)


#----------------------------------------фильтруем БД по городу или специальности---------------------------------------------------------------
    city = request.GET.get('city')
    specialization = request.GET.get('specialization')

    context = {'city': city, 'specialization': specialization, 'title': 'Job Finder', 'form': form}
    if city or specialization:
        _filter = {} #словарь заполняем ниже
        if city:
            #словарь    #ключ   #значение
            _filter['city__slug'] = city       #чтобы обратиться к городу по его слагу или имени необходимо двойное подчеркивание
        if specialization:
            #словарь             # ключ       #значение
            _filter['specialization__slug'] = specialization
# ----------------------------------------фильтруем БД по городу или специальности---------------------------------------------------------------


        qs = Vacancy.objects.filter(**_filter) # две звездочки - разворачиваем словарь (раскрываем) присваивая объектам класса Vacancy значения из словаря фильтруя их по этим же значениям

        paginator = Paginator(qs, 10)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['objects_list']= page_obj


    return render(request, "main_navbar.html", context)

src/scraping/templates/Navbar.html
{% extends 'base.html' %}
{% load static %}


    <!-- Page Content -->
    {% block content %}

    {% endblock content %}


    <!-- Footer -->
    {% block footer %}

    {% endblock footer %}



    

src/scraping/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{title|title}}</title>
    <link rel="stylesheet" href="{% static 'css/style_of_main_button.css' %}" />
    <link rel="stylesheet" href="{% static 'css/pagination.css' %}" />
    <link rel="stylesheet" href="{% static 'css/stiyles_fonts_nav_footer.css' %}" />
</head>
<body>

    <div id="header">


        <p></p>
        <h1><strong>&nbsp;&nbsp;&nbsp;&nbsp;</strong>Job Finder</h1>

        {% if user.is_authenticated %}
        <h2><a href="{% url 'accounts:logout_views' %}">Выйти из аккаунта - ({{ user }})&nbsp;&nbsp;</a>
        {% else %}
        <h2><a href="{% url 'accounts:login_views' %}">Войти&nbsp;&nbsp;</a>
            <a href="{% url 'accounts:register_views' %}">Регистрация&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
        </h2>
         {% endif %}
    </div>
    <div id="nav">
        <ul>
            <li><a href="#" id="pull">Домашняя страница</a></li>
            <li><a href="#"><span>Posts</span></a></li>
            <li class="dropdown"><a href="#"><span>Ресурсы для поиска</span></a>
                <ul>
                    <li><a href="#"><span>1</span></a></li>
                    <li><a href="#"><span>2</span></a></li>
                    <li><a href="#"><span>3</span></a></li>
                    <li><a href="#"><span>4</span></a></li>
                    <li><a href="#"><span>5</span></a></li>
                </ul>
            </li>
            <li class="dropdown"><a href="#"><span>Settings</span></a>
                <ul>
                    <li><a href="#"><span>1</span></a></li>
                    <li><a href="#"><span>2</span></a></li>
                    <li><a href="#"><span>3</span></a></li>
                    <li><a href="#"><span>4</span></a></li>
                    <li><a href="#"><span>5</span></a></li>
                </ul>
            </li>
            <li><a href="#"><span>Личный кабинет</span></a></li>
        </ul>
    </div>
<!-----------------------------block content--------------------------------------------------------->
    <style>
        .text_center{
        color: #111;
        font-size: 16px;
        font-weight: normal;
        letter-spacing: -1px;
        margin: 2% 10% 10% 10%;
        }
    </style>
    <div class="text_center">
    <!-- Page Content -->
    {% block content %}

    {% endblock content %}
    </div>
<!-----------------------------end block content--------------------------------------------------------->

<!-- Footer -->
     <div id="footer">
       &copy; Made by TRAMPlin30
     </div>

</body>
</html>



    

src/scraping/templates/main_index.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{{title|title}}</title>
    <link rel="stylesheet" href="{% static 'css/style_of_main_button.css' %}" />
    <link rel="stylesheet" href="{% static 'images/pixarbay.png' %}" />
    <style>
        body {
            background:
                #f7c40d
                /* Цвет фона */
                url({% static 'images/pixarbay.png' %})
                /* Путь к файлу с рисунком фона */
                center
                /* Положение в правом верхнем углу */
                no-repeat
                /* Не повторять рисунок */
                fixed;
            /* Зафиксировать фон */
        }

        h1 {
            font-family: Arial, sans-serif;
            font-size: 1.2em;
        }
    </style>
</head>

<body>
    <div class="center">
        <a href="{% url 'scraping:main_navbar' %}" class="border-button">Click here to find a job!</a>
    </div>
</body>

</html>

src/scraping/templates/main_navbar.html
{% extends 'base.html' %}
{% load static %}


    <!-- Page Content -->
    {% block content %}

<!-- форма для поиска вакансий -->
        <div class="center">
        <div class="center"> <!-- раздел который занимает 4 колонки на странице (ограничивает поле до 4х колонок)-->
          <form action="" method="GET">
             {% csrf_token %}
             {{ form.as_p }}
             <button type="submit" class="border-button">Собрать информацию о вакансиях!</button>
          </form>
        </div>
        </div>
<!-- форма для поиска вакансий -->


        <style>
        .text_h3 {
            font-size: 26px;}
        </style>

        {% for object in objects_list %}
        <div class="text_h3">
        <a href="{{ object.url }}">{{ object.title }}</a>
        </div>
        <p>Расположение: г.{{ object.city.name }}</p>
        <p>Организация: {{ object.company }}</p>
        <p>{{ object.description }}</p>
        <p><small>{{ object.timestamp }}</small></p>
        <p><small>_________________________</small></p>
        <div><p></p></div>
        {% empty %}
        <div class="center">
        <h1><strong></strong>К сожелению, по Вашему запросу ничего не найдено...</h1>
        </div>
        {% endfor %}


<!-- Пагинация страниц отображения -->
<!--<link rel="stylesheet" href="{% static 'css/pagination.css' %}" />-->

{% if objects_list %}
<div class="center">
        <ul class="pagination">


                {% if objects_list.has_previous %}
                    <li>
                        <a href="?city={{ city }}&specialization={{ specialization }}&page=1" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}


                    {% for page in objects_list.paginator.page_range %}
                        <li class="{% if page == objects_list.number %} active {% endif %}">
                            <a href="?city={{ city }}&specialization={{ specialization }}&page={{ page }}">{{ page }}</a>
                        </li>
                    {% endfor %}


                {% if objects_list.has_next %}
                    <li>
                        <a href="?city={{ city }}&specialization={{ specialization }}&page={{ objects_list.next_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}


        </ul>
</div>
{% endif %}

<!--Page {{ objects_list.number }} of {{ objects_list.paginator.num_pages }}-->
<!-- Пагинация страниц отображения -->



    {% endblock content %}